[package]
name = "ximu3"
version = "0.0.0"
authors = ["x-io Technologies Limited <info@x-io.co.uk>"]
edition = "2018"
description = "x-IMU3 API"
repository = "https://github.com/xioTechnologies/x-IMU3-Software"
license = "MIT"
build = "build.rs"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
crossbeam = "0.8.1"
libc = "0.2.111"
regex = "1.5.4"
scan_fmt = "0.2.6"
serde = "1.0.131"
serde_json = "1.0.72"
serialport = "4.0.1"

[build-dependencies]
cbindgen = { git = "https://github.com/eqrion/cbindgen" } # TODO: Use version >v0.20.0 once avalaible
